# -*- coding: utf-8 -*-
"""VITsneha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnD4JFXwZRj4CP9Nfj5-9eIbKNbhbfW_
"""

import csv

data = [
    ["Name", "Marks"],
    ["Aarav", 78],
    ["Riya", 92],
    ["Kabir", 67],
    ["Aisha", 85],
    ["Manav", 73]
]

with open("Book1.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerows(data)

print("CSV file created successfully!")

import matplotlib.pyplot as plt
import csv
import statistics

# function to load data

def load_marks(filename):
  students=[]
  marks=[]

  try:
    with open(filename,"r") as file:
      reader=csv.reader(file)
      next(reader)

      for row in reader:
        students.append(row[0])
        marks.append(float(row[1]))

    return students,marks

  except FileNotFoundError:
    print("ERROR: File not found!")
    return [],[]

# Analyze student performance

def analyze_performance(marks):
  if not marks:
    return None

  return {
      "mean": statistics.mean(marks),
      "median": statistics.median(marks),
      "highest": max(marks),
      "lowest": min(marks),
      "stdev": statistics.stdev(marks) if len(marks)>1 else 0
  }

# Plot performance graph

def plot_fig(students,marks):
  plt.figure(figsize=(10,5))
  plt.bar(students,marks)
  plt.xlabel("Students")
  plt.ylabel("marks")
  plt.title("Student Performance Chart")
  plt.xticks()
  plt.show()

# Main Program

filename='Book1.csv'

students,marks=load_marks(filename)

if students:
  stats = analyze_performance(marks)

  print("\n------ Student Performance Report ------")
  print(f"Average Marks : {stats['mean']}")
  print(f"Median Marks : {stats['median']}")
  print(f"Highest Marks : {stats['highest']}")
  print(f"Lowest Marks : {stats['lowest']}")
  print(f"Std Deviation : {stats['stdev']}")
  print("------------------------------------------")

  plot_fig(students,marks)